networks:
  app-network:
    driver: bridge

services:
  manticore:
    image: manticoresearch/manticore:latest
    restart: unless-stopped
    ports:
      - "9306:9306"
      - "9312:9312"
    volumes:
      - ./manticore.development.conf:/etc/manticoresearch/manticore.conf
      - manticore_data:/var/lib/manticore
      - manticore_logs:/var/log/manticore
    environment:
      - EXTRA=1
    command: ["/bin/sh", "-c", "searchd --config /etc/manticoresearch/manticore.conf --console"]
    networks:
      - app-network


volumes:
  manticore_data:
  manticore_logs:
