version: '3.8'

services:
  manticore:
    image: manticoresearch/manticore:latest
    restart: always
    network_mode: "host"
    ports:
      - "9306:9306"
      - "9312:9312"
    volumes:
      - ./manticore.development.conf:/etc/manticoresearch/manticore.conf
      - manticore_data:/var/lib/manticore
      - ./logs:/var/log/manticore
    depends_on:
      - mysql
    environment:
      - TZ=${tz}
    command: ["/bin/sh", "-c", "searchd --config /etc/manticoresearch/manticore.conf"]
  
  manticore-indexer:
    image: manticoresearch/manticore:latest
    restart: always
    network_mode: "host"
    volumes:
      - ./manticore.development.conf:/etc/manticoresearch/manticore.conf
      - manticore_data:/var/lib/manticore
    depends_on:
      - manticore
      - mysql
    command: ["/bin/sh", "-c", "while true; do indexer --config /etc/manticoresearch/manticore.conf --all --rotate; sleep 300; done"]
    environment:
      - TZ=${tz}

  mysql:
    image: mysql:8.0
    restart: always
    network_mode: "host"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${mysql_database}
      MYSQL_USER: ${mysql_user}
      MYSQL_PASSWORD: ${mysql_password}
      MYSQL_ROOT_PASSWORD: ${mysql_root_password}
      TZ: ${tz}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./documents/database/all-db-definition.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  manticore_data:
  mysql_data:
