networks:
  app-network:
    driver: bridge

services:
  manticore:
    image: manticoresearch/manticore:latest
    restart: always
    ports:
      - "9306:9306"
      - "9312:9312"
    volumes:
      - ./manticore.development.conf:/etc/manticoresearch/manticore.conf
      - manticore_data:/var/lib/manticore
      - ./logs:/var/log/manticore
    depends_on:
      - mysql
    environment:
      - TZ=${tz}
    command: ["/bin/sh", "-c", "searchd --config /etc/manticoresearch/manticore.conf"]
    networks:
      - app-network

  manticore-indexer:
    image: manticoresearch/manticore:latest
    restart: always
    volumes:
      - ./manticore.development.conf:/etc/manticoresearch/manticore.conf
      - manticore_data:/var/lib/manticore
    depends_on:
      - manticore
      - mysql
    command: ["/bin/sh", "-c", "while true; do indexer --config /etc/manticoresearch/manticore.conf --all --rotate; sleep 300; done"]
    environment:
      - TZ=${tz}
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "${mysql_port}:3306"
    environment:
      MYSQL_DATABASE: ${mysql_database}
      MYSQL_USER: ${mysql_user}
      MYSQL_PASSWORD: ${mysql_password}
      MYSQL_ROOT_PASSWORD: ${mysql_root_password}
      TZ: ${tz}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  manticore_data:
  mysql_data:
