version: '3.4'

services:

  document:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "18081:80"
    volumes:
      - ../..:/www
      - ../../../db-backup:/www/db-backup
      - ../../../local-db-backup:/www/local-db-backup
      - ./nginx:/etc/nginx/conf.d
      - ${HOME}/.htpasswd:/etc/apache2/.htpasswd
